### ISSUE TITLE
[bug] Media pruning throws a "multiple assignments to same column" pgsql error

### ISSUE THREAD

**Issue by trysdyn** [superseriousbusiness/gotosocial#1645]
### Describe the bug with a clear and concise description of what the bug is.

Attempting to execute a media prune either via the admin web interface or CLI (and I presume the scheduled one given the disk consumption trend lately) fails with a database error and appears to not actually prune anything.

### What's your GoToSocial Version?

GoToSocial v0.7.1 git-e8595f0

### GoToSocial Arch

x86_64 source build

### What happened?

I got a disk usage alert today, which is surprising given my aggressive media pruning. I attempted to use the web interface to execute a media prune; 20 minutes later I found it did nothing, so I shut GtS down and attempted a prune from the CLI.

Here's the output, with a dry run attempted immediately after to demonstrate 13k items remain unpruned.

I see two issues here; the constraint failure on `updated_at` and an error cleaning up and trying to tear down an account cache that I presume is not even spun up in this mode.

```
[gotosocial@electric ~]$ ./gotosocial admin media prune remote --config-path config.yaml --dry-run=false
timestamp="23/03/2023 17:23:01.079" func=bundb.pgConn level=INFO msg="connected to POSTGRES database"
timestamp="23/03/2023 17:23:01.085" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
2023/03/23 17:23:35 error executing command: error pruning: ERROR: multiple assignments to same column "updated_at" (SQLSTATE 42601)

[gotosocial@electric ~]$ ./gotosocial admin media prune remote --config-path config.yaml
timestamp="23/03/2023 17:23:55.265" func=bundb.pgConn level=INFO msg="connected to POSTGRES database"
timestamp="23/03/2023 17:23:55.272" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
timestamp="23/03/2023 17:24:28.495" func=prune.glob..func2 level=INFO msg="DRY RUN: 13214 remote items are unused/stale and eligible to be pruned"
timestamp="23/03/2023 17:24:28.496" func=bundb.(*basicDB).Stop level=INFO msg="closing db connection"
timestamp="23/03/2023 17:24:28.496" func=cache.tryUntil level=PANIC msg="failed stopping gtsmodel.Account cache after 5 tries"
panic: failed stopping gtsmodel.Account cache after 5 tries

goroutine 1 [running]:
github.com/superseriousbusiness/gotosocial/internal/log.Panicf.func1()
	github.com/superseriousbusiness/gotosocial/internal/log/log.go:139 +0x2a
github.com/superseriousbusiness/gotosocial/internal/log.Panicf({0x0, 0x0}, {0x25e7afa, 0x18}, {0xc000f0fa60, 0x2, 0x2})
	github.com/superseriousbusiness/gotosocial/internal/log/log.go:141 +0x139
github.com/superseriousbusiness/gotosocial/internal/cache.tryUntil({0x25f7705, 0x1f}, 0x5, 0xc000f0fb70)
	github.com/superseriousbusiness/gotosocial/internal/cache/util.go:37 +0xdb
github.com/superseriousbusiness/gotosocial/internal/cache.(*gtsCaches).Stop(0xc000948700)
	github.com/superseriousbusiness/gotosocial/internal/cache/gts.go:159 +0x6f
github.com/superseriousbusiness/gotosocial/internal/cache.(*Caches).Stop(0xc00095c500)
	github.com/superseriousbusiness/gotosocial/internal/cache/cache.go:57 +0x29
github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/media/prune.(*prune).shutdown(0xc0007ba4e0, {0x2b10178, 0xc0000420b8})
	github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/media/prune/common.go:78 +0xf5
github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/media/prune.glob..func2({0x2b10178, 0xc0000420b8})
	github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/admin/media/prune/remote.go:56 +0x28a
main.run({0x2b10178, 0xc0000420b8}, 0x268ed30)
	github.com/superseriousbusiness/gotosocial/cmd/gotosocial/common.go:81 +0x12c
main.adminCommands.func20(0xc0009c9b00?, {0x25b9a8f?, 0x2?, 0x2?})
	github.com/superseriousbusiness/gotosocial/cmd/gotosocial/admin.go:192 +0x31
github.com/spf13/cobra.(*Command).execute(0xc0009c9b00, {0xc0003c3240, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008c0c00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	github.com/superseriousbusiness/gotosocial/cmd/gotosocial/main.go:74 +0x1dd
```

### What you expected to happen?

Pruning to work and for my precious, precious disk space to return to me

### How to reproduce it?

Attempt a non dry-run media prune, at least presuming it's a code issue and not something beefed in my database.

### Anything else we need to know?

At the same time this started, I also dropped media-remote-cache-days from 7 to 3; but I can't imagine that'd make a difference.

**Comment by tsmethurst** [comment]
Ah thank you! Think I know what the issue is here. Helpful logs :)

**Comment by NyaaaWhatsUpDoc** [comment]
Ah yep this'll be the recently updated columns check in the media update query handler.
