### ISSUE TITLE
[bug] Moshidon crashes when clicking the compose post button

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#1862]
### Describe the bug with a clear and concise description of what the bug is.

Moshidon crashes when clicking the compose post button.

### What's your GoToSocial Version?

v0.9.0 git-282be6f

### GoToSocial Arch

amd64 Docker

### What happened?

Moshidon error log:
```log
[Stack Trace]:
java.lang.RuntimeException: java.lang.UnsupportedOperationException
 at me.grishka.appkit.b.b(SourceFile:36)
 at org.joinmastodon.android.fragments.BaseStatusListFragment.onFabClick(SourceFile:19)
 at org.joinmastodon.android.fragments.HomeTabFragment.onFabClick(SourceFile:17)
 at org.joinmastodon.android.fragments.HomeTabFragment.u(Unknown Source:0)
 at org.joinmastodon.android.fragments.o4.onClick(Unknown Source:2)
 at android.view.View.performClick(View.java:7506)
 at android.view.View.performClickInternal(View.java:7483)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:29357)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7934)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.UnsupportedOperationException
 at java.util.AbstractList.add(AbstractList.java:153)
 at org.joinmastodon.android.ui.CustomEmojiPopupKeyboard.onCreateView(SourceFile:188)
 at org.joinmastodon.android.ui.PopupKeyboard.ensureView(SourceFile:5)
 at org.joinmastodon.android.ui.PopupKeyboard.getView(SourceFile:1)
 at org.joinmastodon.android.fragments.ComposeFragment.onCreateContentView(SourceFile:68)
 at me.grishka.appkit.fragments.f.onCreateView(SourceFile:18)
 at android.app.Fragment.performCreateView(Fragment.java:2505)
 at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
 at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
 at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
 at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
 at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
 at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:822)
 at me.grishka.appkit.a.showFragment(SourceFile:67)
 at me.grishka.appkit.b.b(SourceFile:29)
 ... 16 more
```

### What you expected to happen?

Users can toot normally from moshidon to gotosocial server.

### How to reproduce it?

1. Install moshidon from [github repo](https://github.com/LucasGGamerM/moshidon)
2. Login to a GTS instance
3. Click the compose ✏️ button in the bottom right corner

### Anything else we need to know?

I'm hosting my instance at a subdomain, while using the main domain `@example.org` in my username?

**Comment by tsmethurst** [comment]
Heya, this sounds like an issue to open on their repo, so they can help decode the logs and see what's going on. My first guess would be that it might be something to do with GtS requiring an auth token at the custom emojis endpoint, unlike other fedi servers, but not sure.

**Comment by CDN18** [comment]
I agree that it seems to be related to the emoji API. However, there is a slight difference in the behavior between Mastodon and GTS on Moshidon. While Mastodon allows enabling token authentication for APIs through environment variables, enabling this mode (`AUTHORIZED_FETCH`) on a Mastodon instance does not cause Moshidon to crash. It simply restricts users from selecting emojis within Moshidon.

**Comment by CDN18** [comment]
The latest nightly version of moshidon fixed this issue 🥳
