### ISSUE TITLE
[bug] Errors when using `toot`, the mastodon CLI client.

### ISSUE THREAD

**Issue by theblacksquid** [superseriousbusiness/gotosocial#192]
I was able to log into my testing instance by doing

`toot login`

and logging in with my email and password on the browser window that pops up. After clicking on "Allow", i opened the `F12` menu, went to the console, and copied the oauth string back into the awaiting prompt on the terminal.

Posting using `toot post` works, but printing the timeline with `toot timeline` and viewing the tui using `toot curses` returned errors

```
<my super-secret-prompt>$ toot curses
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.21.0', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 480, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 456, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 74, in curses
    TimelineApp(app, user, generator).run()
  File "/usr/lib/python3/dist-packages/toot/ui/app.py", line 327, in run
    curses.wrapper(self._wrapped_run)
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3/dist-packages/toot/ui/app.py", line 336, in _wrapped_run
    self.fetch_next()
  File "/usr/lib/python3/dist-packages/toot/ui/app.py", line 480, in fetch_next
    self.statuses.append(parse_status(status))
  File "/usr/lib/python3/dist-packages/toot/ui/parsers.py", line 11, in parse_status
    boosted_by = parse_account(status['account']) if status['reblog'] else None
KeyError: 'reblog'
<my super-secret-prompt>$ toot timeline
────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.21.0', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 480, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 456, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 46, in timeline
    print_timeline(items)
  File "/usr/lib/python3/dist-packages/toot/output.py", line 176, in print_timeline
    print_status(item, width)
  File "/usr/lib/python3/dist-packages/toot/output.py", line 130, in print_status
    reblog = status['reblog']
KeyError: 'reblog'
```

**Comment by ffuentese** [comment]
I have the same issue

[!img](https://imgur.com/TtuFW1d.png)

**Comment by igalic** [comment]
> @theblacksquid and logging in with my email and password on the browser window that pops up. After clicking on "Allow", i opened the F12 menu, went to the console, and copied the oauth string back into the awaiting prompt on the terminal.

where, and, how, exactly, did you get the OAuth string?
