### ISSUE TITLE
[bug] Duplicate Account Keys causes crash of Official Mastodon Android App

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2226]
### Describe the bug with a clear and concise description of what the bug is.

Some of the users on my Gotosocial instance encountered application crashes after logging in with the Android App. The crashes occurred when accessing their own profiles.

### What's your GoToSocial Version?

v0.11.1-SNAPSHOT git-9f9fcf7

### GoToSocial Arch

amd64 Docker

### What happened?

- User logs in to the GTS instance via Android APP (Official Mastodon App or its forks like Moshidon)
- User goes to their profile.
- The application crashes due to a "Duplicate Key" error (stacktrace pasted below).

-----

#### Mastodon Official App
```
[Package Name]: org.joinmastodon.android
[Version Name]: 2.1.1
[Version Code]: 67
[Error Type]: JVM
[Crash Time]: 2023-09-26T02:33:01.583
[Stack Trace]:
java.lang.IllegalStateException: Duplicate key https://<gotosocial url>/@user1 (attempted merging values 017NQ2MY51KK43N2W3NPPYY8Y4 and 017NQ2MY51KK43N2W3NPPYY8Y4)
 at j$.util.stream.Collectors.a(SourceFile:0)
 at j$.util.stream.n.accept(Unknown Source:10)
 at j$.util.stream.Q1.accept(Unknown Source:4)
 at j$.util.a.forEachRemaining(SourceFile:0)
 at j$.util.stream.c.c0(SourceFile:0)
 at j$.util.stream.c.F0(Unknown Source:10)
 at j$.util.stream.D0.v(Unknown Source:4)
 at j$.util.stream.c.I0(SourceFile:0)
 at j$.util.stream.n2.collect(SourceFile:0)
 at org.joinmastodon.android.ui.text.b.l(SourceFile:19)
 at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.b(SourceFile:25)
 at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.c(Unknown Source:10)
 at x0.e3.O1(Unknown Source:9)
 at x0.e3.Z0(Unknown Source:2)
 at x0.h.h(SourceFile:42)
 at b0.h.d(SourceFile:62)
 at v.f.x0(SourceFile:29)
 at x0.b.Y1(Unknown Source:0)
 at x0.b$a.a(SourceFile:31)
 at x0.b$a.onSuccess(Unknown Source:2)
 at u.a$a.run(SourceFile:12)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7968)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

#### Moshidon (fork of Mastodon official Android App)
```
[Package Name]: org.joinmastodon.android.moshinda.nightly
[Version Name]: 1.2.3+fork.101.moshinda-nightly+@2023-09-22
[Version Code]: 101
[Error Type]: JVM
[Crash Time]: 2023-09-26T01:51:02.261
[Stack Trace]:
java.lang.IllegalStateException: Duplicate key https://<gotosocial url>/@user1 (attempted merging values 017NQ2MY51KK43N2W3NPPYY8Y4 and 017NQ2MY51KK43N2W3NPPYY8Y4)
 at j$.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(SourceFile:0)
 at j$.util.stream.MatchOps$$ExternalSyntheticLambda0.accept(Unknown Source:10)
 at j$.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source:4)
 at j$.util.stream.ReferencePipeline$2$1.accept(SourceFile:0)
 at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(SourceFile:0)
 at j$.util.stream.AbstractPipeline.copyInto(SourceFile:0)
 at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
 at j$.util.stream.Node$-CC.evaluateSequential(Unknown Source:4)
 at j$.util.stream.AbstractPipeline.evaluate(SourceFile:0)
 at j$.util.stream.ReferencePipeline.collect(SourceFile:0)
 at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:103)
 at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.buildItems(StatusDisplayItem.java:246)
 at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:54)
 at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:41)
 at org.joinmastodon.android.fragments.BaseStatusListFragment.onAppendItems(BaseStatusListFragment.java:137)
 at me.grishka.appkit.utils.Preloader.onDataLoaded(Preloader.java:86)
 at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(BaseRecyclerFragment.java:327)
 at org.joinmastodon.android.fragments.BaseStatusListFragment.onDataLoaded(BaseStatusListFragment.java:878)
 at org.joinmastodon.android.fragments.AccountTimelineFragment$1.onSuccess(AccountTimelineFragment.java:66)
 at org.joinmastodon.android.fragments.AccountTimelineFragment$1.onSuccess(AccountTimelineFragment.java:59)
 at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7968)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

### What you expected to happen?

Account profiles loads successfully.

### How to reproduce it?

Newly created accounts do not have this problem. `@user1` blocked `@user2`, the account that was having the issue, and then unblocked it.

The request logs show that the api causing the crash ~~is probably `/api/v1/accounts/01GHP0HG1RX1NAN7X9PY6CE5D3/statuses`, where `01GHP0HG1RX1NAN7X9PY6CE5D3` is the user's own account ID for the user who is experiencing crashes (`@user2`)~~ , and the logs are as follows:

Edit: After checking the response of `/api/v1/accounts/01GHP0HG1RX1NAN7X9PY6CE5D3/statuses`, I found no relevant status of `@user1` (AccountID:` 017NQ2MY51KK43N2W3NPPYY8Y4 `)

```
gotosocial  | timestamp="25/09/2023 18:08:47.387" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.954425ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/preferences clientIP=0.0.0.0 requestID=366rfkca04001a81yv60 msg="OK: wrote 132B"
gotosocial  | timestamp="25/09/2023 18:08:47.392" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.736597ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/lists clientIP=0.0.0.0 requestID=3t6rfkca040004geek60 msg="OK: wrote 26B"
gotosocial  | timestamp="25/09/2023 18:08:47.396" func=server.glob..func1.Logger.func13.1 level=INFO latency="2.074099ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/instance clientIP=0.0.0.0 requestID=4a6rfkca04001ffe0mgg msg="OK: wrote 1.13kiB"
gotosocial  | timestamp="25/09/2023 18:08:47.397" func=server.glob..func1.Logger.func13.1 level=INFO latency="518.131µs" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/filters clientIP=0.0.0.0 requestID=4p6rfkca0400176rcfcg msg="OK: wrote 26B"
gotosocial  | timestamp="25/09/2023 18:08:47.399" func=server.glob..func1.Logger.func13.1 level=INFO latency="3.327658ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/accounts/verify_credentials clientIP=0.0.0.0 requestID=4e6rfkca04000ztyrxng msg="OK: wrote 689B"
gotosocial  | timestamp="25/09/2023 18:08:47.731" func=server.glob..func1.Logger.func13.1 level=INFO latency="66.083µs" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=404 path=/api/v1/followed_tags clientIP=0.0.0.0 requestID=ee78fkca040005grz9m0 msg="Not Found: wrote 21B"
gotosocial  | timestamp="25/09/2023 18:08:47.734" func=server.glob..func1.Logger.func13.1 level=INFO latency="28.481µs" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=404 path=/api/v1/announcements clientIP=0.0.0.0 requestID=et78fkca04000fqz1140 msg="Not Found: wrote 21B"
gotosocial  | timestamp="25/09/2023 18:08:47.744" func=server.glob..func1.Logger.func13.1 level=INFO latency="819.472µs" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/markers clientIP=0.0.0.0 requestID=g278fkca04000pb69beg msg="OK: wrote 182B"
gotosocial  | timestamp="25/09/2023 18:08:47.783" func=server.glob..func1.Logger.func13.1 level=INFO latency="3.189301ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/timelines/home clientIP=0.0.0.0 requestID=me78fkca040007xg8j0g msg="OK: wrote 1.32kiB"
gotosocial  | timestamp="25/09/2023 18:08:47.829" func=server.glob..func1.Logger.func13.1 level=INFO latency="82.516908ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/notifications clientIP=0.0.0.0 requestID=ga78fkca04001zgmmchg msg="OK: wrote 9.55kiB"
gotosocial  | timestamp="25/09/2023 18:08:48.074" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.011308ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/markers clientIP=0.0.0.0 requestID=s67rfkca040005wxr540 msg="OK: wrote 182B"
gotosocial  | timestamp="25/09/2023 18:08:48.076" func=server.glob..func1.Logger.func13.1 level=INFO latency="1.392073ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/accounts/01GHP0HG1RX1NAN7X9PY6CE5D3/statuses clientIP=0.0.0.0 requestID=se7rfkca04001z62esc0 msg="OK: wrote 26B"
gotosocial  | timestamp="25/09/2023 18:08:48.127" func=server.glob..func1.Logger.func13.1 level=INFO latency="162.246µs" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=401 path=/api/v1/custom_emojis clientIP=0.0.0.0 requestID=zy7rfkca040011xc39fg msg="Unauthorized: wrote 68B"
gotosocial  | timestamp="25/09/2023 18:08:48.135" func=server.glob..func1.Logger.func13.1 level=INFO latency="47.332181ms" userAgent=MoshidonAndroid/1.2.3+fork.101.moshinda-nightly+@2023-09-22 method=GET statusCode=200 path=/api/v1/accounts/01GHP0HG1RX1NAN7X9PY6CE5D3/statuses clientIP=0.0.0.0 requestID=v27rfkca04001rxzyggg msg="OK: wrote 25.5kiB"
```

### Anything else we need to know?

I reviewed the `follows` and `follow_requests` tables and discovered multiple follow requests associated with the account ID `017NQ2MY51KK43N2W3NPPYY8Y4`, which was the ID of the account causing the crash. I manually deleted those records, but unfortunately, the issue persists.

**Comment by tsmethurst** [comment]
What on earth, what a strange bug! Thanks for opening.

**Comment by tsmethurst** [comment]
^^ I opened an issue on the Mastodon Android repo to see if they have any insight into this :)

**Comment by CDN18** [comment]
Thanks very much for helping to bring the issue upstream! I have tested the latest commit from the mastodon app developer, and it successfully resolved the problem without any crashes or other issues.
