### ISSUE TITLE
[bug] panic: interface conversion: *stdlib.Conn is not bundb.conn: missing method Exec

### ISSUE THREAD

**Issue by CDN18** [superseriousbusiness/gotosocial#2635]
### Describe the bug with a clear and concise description of what the bug is.

Latest snapshot (ede8f43) crashes upon initiating.

## Log

```
gotosocial  | timestamp="13/02/2024 01:39:40.920" func=cache.(*Caches).Init level=INFO msg="init: 0x40001a7c00"
gotosocial  | timestamp="13/02/2024 01:39:40.920" func=cache.(*Caches).initAccount level=INFO msg="cache size = 4655"
gotosocial  | timestamp="13/02/2024 01:39:40.921" func=cache.(*Caches).initAccountCounts level=INFO msg="cache size = 4655"
gotosocial  | timestamp="13/02/2024 01:39:40.921" func=cache.(*Caches).initAccountNote level=INFO msg="cache size = 2170"
gotosocial  | timestamp="13/02/2024 01:39:40.921" func=cache.(*Caches).initApplication level=INFO msg="cache size = 193"
gotosocial  | timestamp="13/02/2024 01:39:40.921" func=cache.(*Caches).initBlock level=INFO msg="cache size = 6580"
gotosocial  | timestamp="13/02/2024 01:39:40.922" func=cache.(*Caches).initBlockIDs level=INFO msg="cache size = 1213"
gotosocial  | timestamp="13/02/2024 01:39:40.922" func=cache.(*Caches).initBoostOfIDs level=INFO msg="cache size = 1213"
gotosocial  | timestamp="13/02/2024 01:39:40.922" func=cache.(*Caches).initEmoji level=INFO msg="cache size = 4521"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initEmojiCategory level=INFO msg="cache size = 245"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initFollow level=INFO msg="cache size = 4285"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initFollowIDs level=INFO msg="cache size = 1618"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initFollowRequest level=INFO msg="cache size = 4285"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initFollowRequestIDs level=INFO msg="cache size = 809"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initInReplyToIDs level=INFO msg="cache size = 1213"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initInstance level=INFO msg="cache size = 1210"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initList level=INFO msg="cache size = 2170"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initListEntry level=INFO msg="cache size = 4838"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initMarker level=INFO msg="cache size = 1245"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initMedia level=INFO msg="cache size = 4369"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initMention level=INFO msg="cache size = 3909"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initNotification level=INFO msg="cache size = 4416"
gotosocial  | timestamp="13/02/2024 01:39:40.923" func=cache.(*Caches).initPoll level=INFO msg="cache size = 1908"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initPollVote level=INFO msg="cache size = 4623"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initPollVoteIDs level=INFO msg="cache size = 809"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initReport level=INFO msg="cache size = 1320"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initStatus level=INFO msg="cache size = 4726"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initStatusFave level=INFO msg="cache size = 4253"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initTag level=INFO msg="cache size = 4789"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initThreadMute level=INFO msg="cache size = 489"
gotosocial  | timestamp="13/02/2024 01:39:40.924" func=cache.(*Caches).initStatusFaveIDs level=INFO msg="cache size = 1213"
gotosocial  | timestamp="13/02/2024 01:39:40.925" func=cache.(*Caches).initTombstone level=INFO msg="cache size = 1124"
gotosocial  | timestamp="13/02/2024 01:39:40.925" func=cache.(*Caches).initUser level=INFO msg="cache size = 329"
gotosocial  | timestamp="13/02/2024 01:39:40.925" func=cache.(*Caches).initWebfinger level=INFO msg="cache size = 1360"
gotosocial  | timestamp="13/02/2024 01:39:40.925" func=cache.(*Caches).initVisibility level=INFO msg="Visibility cache size = 5332"
gotosocial  | timestamp="13/02/2024 01:39:40.925" func=cache.(*Caches).Start level=INFO msg="start: 0x40001a7c00"
gotosocial  | timestamp="13/02/2024 01:39:40.935" func=cache.(*Caches).Stop level=INFO msg="stop: 0x40001a7c00"
gotosocial  | panic: interface conversion: *stdlib.Conn is not bundb.conn: missing method Exec
gotosocial  | 
gotosocial  | goroutine 1 [running]:
gotosocial  | github.com/superseriousbusiness/gotosocial/internal/db/bundb.(*PostgreSQLDriver).Open(0x40005ad0c8?, {0x4000168180?, 0x40005ad088?})
gotosocial  |      /drone/src/internal/db/bundb/drivers.go:57 +0x60
gotosocial  | database/sql.dsnConnector.Connect(...)
gotosocial  |      /usr/local/go/src/database/sql/sql.go:758
gotosocial  | database/sql.(*DB).conn(0x4000838270, {0x274ab88, 0x3c83680}, 0x1)
gotosocial  |      /usr/local/go/src/database/sql/sql.go:1387 +0x824
gotosocial  | database/sql.(*DB).PingContext.func1(0x60?)
gotosocial  |      /usr/local/go/src/database/sql/sql.go:850 +0x40
gotosocial  | database/sql.(*DB).retry(0x4000701560?, 0x40005ad2e8)
gotosocial  |      /usr/local/go/src/database/sql/sql.go:1538 +0x4c
gotosocial  | database/sql.(*DB).PingContext(0x4000838270, {0x274ab88, 0x3c83680})
gotosocial  |      /usr/local/go/src/database/sql/sql.go:849 +0x6c
gotosocial  | github.com/superseriousbusiness/gotosocial/internal/db/bundb.pgConn({0x274ab88, 0x3c83680}, 0x4000548000?)
gotosocial  |      /drone/src/internal/db/bundb/bundb.go:308 +0x1cc
gotosocial  | github.com/superseriousbusiness/gotosocial/internal/db/bundb.NewBunDBService({0x274ab88, 0x3c83680}, 0x40001a7c00)
gotosocial  |      /drone/src/internal/db/bundb/bundb.go:131 +0xd0
gotosocial  | github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/server.glob..func1({0x274ab88, 0x3c83680})
gotosocial  |      /drone/src/cmd/gotosocial/action/server/server.go:91 +0x1e0
gotosocial  | main.run({0x274ab88, 0x3c83680}, 0x22cf348)
gotosocial  |      /drone/src/cmd/gotosocial/common.go:82 +0x1b8
gotosocial  | main.serverCommands.func2(0x4000185200?, {0x20cec35?, 0x4?, 0x20cec39?})
gotosocial  |      /drone/src/cmd/gotosocial/server.go:39 +0x30
gotosocial  | github.com/spf13/cobra.(*Command).execute(0x400079f500, {0x3c83680, 0x0, 0x0})
gotosocial  |      /drone/src/vendor/github.com/spf13/cobra/command.go:983 +0x82c
gotosocial  | github.com/spf13/cobra.(*Command).ExecuteC(0x400079ef00)
gotosocial  |      /drone/src/vendor/github.com/spf13/cobra/command.go:1115 +0x344
gotosocial  | github.com/spf13/cobra.(*Command).Execute(...)
gotosocial  |      /drone/src/vendor/github.com/spf13/cobra/command.go:1039
gotosocial  | main.main()
gotosocial  |      /drone/src/cmd/gotosocial/main.go:74 +0x1f0
```

### What's your GoToSocial Version?

snapshot ede8f43635c37a05b72f250632d0b236a2709ca9

### GoToSocial Arch

arm64 Docker

**Comment by NyaaaWhatsUpDoc** [comment]
ah yep that'll be a regression after the latest PR of mine :woman_facepalming: will get right on that now

**Comment by NyaaaWhatsUpDoc** [comment]
@CDN18 if you can check again now, https://github.com/superseriousbusiness/gotosocial/pull/2636 should have fixed this :)

**Comment by CDN18** [comment]
@NyaaaWhatsUpDoc Can confirm it was fixed. Thanks for fixing this ❤️
