### ISSUE TITLE
[bug] domain permissions UI can yield an empty error 

### ISSUE THREAD

**Issue by Pectojin** [superseriousbusiness/gotosocial#3043]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

When using the enter key to submit the form on the domain permissions "blocks" and "allows" pages it results in an error page.

### What's your GoToSocial Version?

v0.16.0

### Browser version

chromium 126 (arm64), firefox 127 (64-bit)

### What happened?

It seems to be some kind of simple front end bug. Clicking the Allow/Block buttons with the mouse works as expected, but using enter key does not.

### How to reproduce it?

Both the blocks and allows pages can be used to replicate
`/settings/moderation/domain-permissions/blocks`
`/settings/moderation/domain-permissions/allows`

Input any text into the "search or add" box then press enter to submit. You can't submit no text and and it doesn't matter if the text is junk or a valid domain.

### Anything else we need to know?

Error page prints:
```
: 

Component trace:
    at DomainPermissionsOverview (https://social.sound-city.dk/assets/dist/settings.js:23061:43)
    at Route (https://social.sound-city.dk/assets/dist/settings.js:19127:2594)
    at Switch (https://social.sound-city.dk/assets/dist/settings.js:19127:3660)
    at ErrorBoundary (https://social.sound-city.dk/assets/dist/settings.js:18511:9)
    at Router (https://social.sound-city.dk/assets/dist/settings.js:19127:1900)
    at ModerationDomainPermsRouter (https://social.sound-city.dk/assets/dist/settings.js:26642:45)
    at Router (https://social.sound-city.dk/assets/dist/settings.js:19127:1900)
    at ModerationRouter (https://social.sound-city.dk/assets/dist/settings.js:26583:45)
    at ErrorBoundary (https://social.sound-city.dk/assets/dist/settings.js:18511:9)
    at Router (https://social.sound-city.dk/assets/dist/settings.js:19127:1900)
    at section
    at App (https://social.sound-city.dk/assets/dist/settings.js:26905:16)
    at Authorization (https://social.sound-city.dk/assets/dist/settings.js:25404:26)
    at t (https://social.sound-city.dk/assets/dist/settings.js:17591:2080)
    at Provider (https://social.sound-city.dk/assets/dist/settings.js:18727:950)
    at Main

Error trace: 
```
(yes, the error trace is empty, it just ends without a newline)

**Comment by tsmethurst** [comment]
Ahh yeah I've seen that too, thanks for opening.
