### ISSUE TITLE
[bug] Unusual crash from nil pointer exception during federation of status delete

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#306]
Haven't seen this one before -- there's a nil pointer in the type converter.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x19e3661]

goroutine 562511 [running]:
github.com/superseriousbusiness/gotosocial/internal/typeutils.(*converter).StatusToAS(0xc000575890, {0x213ad90, 0xc0000b4558}, 0xc001edcf00)
        /drone/src/internal/typeutils/internaltoas.go:479 +0x10c1
github.com/superseriousbusiness/gotosocial/internal/processing.(*processor).federateStatusDelete(0xc0006f0000, {0x213ad90, 0xc0000b4558}, 0x
c001edcf00)
        /drone/src/internal/processing/fromclientapi.go:382 +0x146
github.com/superseriousbusiness/gotosocial/internal/processing.(*processor).processDeleteStatusFromClientAPI(0xc0006f0000, {0x213ad90, 0xc00
00b4558}, {{0x1d66bab, 0x4}, {0x1d6de62, 0x6}, {0x1af9580, 0xc001edcf00}, 0xc001edca00, ...})
        /drone/src/internal/processing/fromclientapi.go:312 +0x237
github.com/superseriousbusiness/gotosocial/internal/processing.(*processor).ProcessFromClientAPI(0xc000cd5370, {0x213ad90, 0xc0000b4558}, {{
0x1d66bab, 0x4}, {0x1d6de62, 0x6}, {0x1af9580, 0xc001edcf00}, 0xc001edca00, ...})
        /drone/src/internal/processing/fromclientapi.go:100 +0x645
github.com/superseriousbusiness/gotosocial/internal/processing.(*processor).Start.func1.1()
        /drone/src/internal/processing/processor.go:314 +0x4f
created by github.com/superseriousbusiness/gotosocial/internal/processing.(*processor).Start.func1
        /drone/src/internal/processing/processor.go:313 +0x2b3
```

**Comment by tsmethurst** [comment]
closed by #322
