### ISSUE TITLE
[bug] Panic in `isStatusHomeTimelineable`

### ISSUE THREAD

**Issue by rnwgnr** [superseriousbusiness/gotosocial#3095]
### Describe the bug with a clear and concise description of what the bug is.

Update to v0.16.0+git-aeb65bc by cross-compiling to ARM64 on a AMD64 system with go 1.22.5

When trying to load the timeline of my account https://clttr.it/@rwphoto GoToSocial PANICs.

```
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x190 pc=0x18ef994]
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: goroutine 4739 [running]:
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/filter/visibility.(*Filter).isStatusHomeTimelineable(0x40020aa7d0, {0x2689f60, 0x5532520}, 0x40037e3c08, 0x400342b208)
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/filter/visibility/home_timeline.go:169 +0x464
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/filter/visibility.(*Filter).StatusHomeTimelineable.func1()
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/filter/visibility/home_timeline.go:47 +0x44
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: codeberg.org/gruf/go-structr.(*Cache[...]).LoadOne(0x26c27c0, 0x40004a6410, {{0x40030b2f30, 0x3, 0x3}, {0x4003826960, 0x50}}, 0x4002453508)
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         codeberg.org/gruf/go-structr@v0.8.7/cache.go:289 +0x298
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/cache.(*StructCache[...]).LoadOne(0x26b2120, {0x1f7a858, 0x4003106bd0?}, 0x4002453508?, {0x40030b2f30, 0x3, 0x3})
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/cache/wrappers.go:129 +0xbc
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/filter/visibility.(*Filter).StatusHomeTimelineable(0x40020aa7d0, {0x2689f60?, 0x5532520?}, 0x4011d68620?, 0x400342b208)
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/filter/visibility/home_timeline.go:45 +0x164
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/server.init.func1.HomeTimelineFilter.5({0x2689f60, 0x5532520}, {0x4011d68620, 0x1a}, {0x268a158?, 0x400342b208})
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/processing/timeline/home.go:79 +0x124
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/timeline.(*timeline).grab(0x400069a640, {0x2689f60, 0x5532520}, 0x9, {0x40157ad4e0, 0x1a}, {0x1f81f4b, 0x1a}, 0x1)
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/timeline/index.go:207 +0x338
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/timeline.(*timeline).indexXBetweenIDs(0x400069a640, {0x2689f60, 0x5532520}, 0x14, {0x40157ad4e0, 0x1a}, {0x1f81f4b, 0x1a}, 0x1)
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/timeline/index.go:122 +0x704
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/timeline.(*timeline).prepareXBetweenIDs(0x400069a640, {0x2689f60, 0x5532520}, 0x14, {0x40157ad4e0, 0x1a}, {0x1f81f4b, 0x1a}, 0x1)
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/timeline/prepare.go:49 +0x28c
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: github.com/superseriousbusiness/gotosocial/internal/timeline.(*timeline).prepareNextQuery.func1()
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/timeline/get.go:403 +0xec
Jul 13 07:31:59 clttr-nbg gotosocial[595061]: created by github.com/superseriousbusiness/gotosocial/internal/timeline.(*timeline).prepareNextQuery in goroutine 4550
Jul 13 07:31:59 clttr-nbg gotosocial[595061]:         github.com/superseriousbusiness/gotosocial/internal/timeline/get.go:398 +0x104
```

**Reverting commit aeb65bceae97611b8931de2e954df18afedd812f fixes this issue.**

Timeline for my second account on this instance at https://clttr.it/@rwa works fine.

### What's your GoToSocial Version?

v0.16.0+git-09b2bee

### GoToSocial Arch

arm64 binary

### What happened?

GoToSocial PANICs, no timeline available.

### What you expected to happen?

Timeline is loaded.

### How to reproduce it?

- be logged in to account @rwphoto@clttr.it
- try to load the status timeline for this account

### Anything else we need to know?

Instance is running on SQLite

**Comment by tsmethurst** [comment]
I'll take a look.

**Comment by rnwgnr** [comment]
Update: reverting commit https://github.com/superseriousbusiness/gotosocial/commit/aeb65bceae97611b8931de2e954df18afedd812f does not fix the issue.

Its more of an intermittent problem, sometimes it loads, sometimes it will PANIC.

This happens for both accounts, not only for the one mentioned in the initial report.

**Comment by tsmethurst** [comment]
Rebooting the vps wouldn't make a difference I'd think.

**Comment by tsmethurst** [comment]
Ah yeah, found it.
