### ISSUE TITLE
[packaging] NixOS

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#412]
Package works, issues are just with the testing:
- included a patch to set a hardcoded path for #411 

- Logging test timeout
```
ok      github.com/superseriousbusiness/gotosocial/internal/federation/federatingdb     0.793s

=== RUN   TestSyslogTestSuite
=== RUN   TestSyslogTestSuite/TestSyslog
time=2022-02-26T01:27:16Z level=warning msg=this is a test of the emergency broadcast system! func=github.com/superseriousbusiness/gotosocial/internal/log_test.(*SyslogTestSuite).TestSyslog file=github.com/superseriousbusiness/gotosocial/internal/log/syslog_test.go:62
panic: test timed out after 10m0s

goroutine 21 [running]:
testing.(*M).startAlarm.func1()
        testing/testing.go:1788 +0x8e
created by time.goFunc
        time/sleep.go:180 +0x31

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000102d00, {0x1baf8a6, 0x46adb3}, 0x1bf64b8)
        testing/testing.go:1307 +0x375
testing.runTests.func1(0xc000365c50)
        testing/testing.go:1598 +0x6e
testing.tRunner(0xc000102d00, 0xc0007ddd18)
        testing/testing.go:1259 +0x102
testing.runTests(0xc000694780, {0x2e43c70, 0x1, 0x1}, {0x48670d, 0x1ba88f3, 0x2e60080})
        testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc000694780)
        testing/testing.go:1504 +0x51d
main.main()
        _testmain.go:45 +0x14b

goroutine 11 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000102ea0, {0x19231c6, 0xc000102ea0}, 0xc0002205a0)
        testing/testing.go:1307 +0x375
github.com/stretchr/testify/suite.runTests({0x1f22df0, 0xc000102ea0}, {0xc000699200, 0x1, 0x1})
        github.com/stretchr/testify@v1.7.0/suite/suite.go:203 +0x124
github.com/stretchr/testify/suite.Run(0xc000102ea0, {0x1efb778, 0xc000365c80})
        github.com/stretchr/testify@v1.7.0/suite/suite.go:176 +0x6e5
github.com/superseriousbusiness/gotosocial/internal/log_test.TestSyslogTestSuite(0x0)
        github.com/superseriousbusiness/gotosocial/internal/log/syslog_test.go:69 +0x39
testing.tRunner(0xc000102ea0, 0x1bf64b8)
        testing/testing.go:1259 +0x102
created by testing.(*T).Run
        testing/testing.go:1306 +0x35a
        goroutine 12 [chan receive, 10 minutes]:
github.com/superseriousbusiness/gotosocial/internal/log_test.(*SyslogTestSuite).TestSyslog(0xc000365c80)
        github.com/superseriousbusiness/gotosocial/internal/log/syslog_test.go:64 +0x78
reflect.Value.call({0xc00004f560, 0xc00068d078, 0x1ba01b5}, {0x1b90eed, 0x4}, {0xc00010fe70, 0x1, 0xc00010fd80})
        reflect/value.go:543 +0x814
reflect.Value.Call({0xc00004f560, 0xc00068d078, 0xc000365c80}, {0xc00010fe70, 0x1, 0x1})
        reflect/value.go:339 +0xc5
github.com/stretchr/testify/suite.Run.func1(0xc000103520)
        github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x4b6
testing.tRunner(0xc000103520, 0xc0002205a0)
        testing/testing.go:1259 +0x102
created by testing.(*T).Run
        testing/testing.go:1306 +0x35a

goroutine 14 [chan receive, 10 minutes]:
gopkg.in/mcuadros/go-syslog%2ev2.(*Server).goParseDatagrams.func1()
        gopkg.in/mcuadros/go-syslog.v2@v2.3.0/server.go:363 +0xdf
created by gopkg.in/mcuadros/go-syslog%2ev2.(*Server).goParseDatagrams
        gopkg.in/mcuadros/go-syslog.v2@v2.3.0/server.go:359 +0x9d

goroutine 15 [IO wait, 10 minutes]:
internal/poll.runtime_pollWait(0x7fffd0e30e88, 0x72)
        runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000298200, 0xc00052a000, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadFrom(0xc000298200, {0xc00052a000, 0x10000, 0x10000})
        internal/poll/fd_unix.go:223 +0x238
net.(*netFD).readFrom(0xc000298200, {0xc00052a000, 0x0, 0x0})
        net/fd_posix.go:62 +0x29
net.(*UDPConn).readFrom(0xc000580000, {0xc00052a000, 0x0, 0x19b8c60}, 0xc00053a000)
        net/udpsock_posix.go:47 +0x3e
net.(*UDPConn).readFromUDP(0xc00068d168, {0xc00052a000, 0x2, 0x0}, 0x2)
        net/udpsock.go:116 +0x31
net.(*UDPConn).ReadFrom(0xc0006a6690, {0xc00052a000, 0x10000, 0x10000})
        net/udpsock.go:125 +0x50
gopkg.in/mcuadros/go-syslog%2ev2.(*Server).goReceiveDatagrams.func1()
        gopkg.in/mcuadros/go-syslog.v2@v2.3.0/server.go:329 +0xd7
created by gopkg.in/mcuadros/go-syslog%2ev2.(*Server).goReceiveDatagrams
        gopkg.in/mcuadros/go-syslog.v2@v2.3.0/server.go:325 +0xaf
FAIL    github.com/superseriousbusiness/gotosocial/internal/log 600.116s
FAIL
```

**Comment by terinjokes** [comment]
I just saw this issue, hello 👋. I've also created a package and module, both of which I'm happy to clean up and share if desired.

I too see these strange test timeouts. I was planning on digging into figuring out why this weekend, if you don't already know.

**Comment by f0x52** [comment]
nice! mine are in [package](https://git.pixie.town/f0x/nixos/src/branch/main/common/packages/gotosocial) and [module](https://git.pixie.town/f0x/nixos/src/branch/main/common/modules/gotosocial.nix). The patch for setting the asset dir can be removed thanks to your PR, but I haven't been able to figure out the weird timeout yet

**Comment by tsmethurst** [comment]
just to add to this, I think the timeouts are related to the syslog tests, but I can't remember if it's been fixed yet or not... did you try it again recently?

**Comment by f0x52** [comment]
still times out

**Comment by f0x52** [comment]
actually, seems it might've been fixed indeed!

**Comment by jtojnar** [comment]
Relevant Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/202110

**Comment by dit7ya** [comment]
@f0x52 your links are returning 502 - is it hosted anywhere else? Also would you be willing to contribute the module to nixpkgs (see linked PR in the above comment)?
