### ISSUE TITLE
[docker] Installation - Error "panic: read /gotosocial/web/template: is a directory"

### ISSUE THREAD

**Issue by pvllnv** [superseriousbusiness/gotosocial#511]
I installed GoToSocial with Docker and got this error message:

```
time=2022-04-29T15:50:45Z level=info msg=connected to SQLITE database
time=2022-04-29T15:50:45Z level=info msg=there are no new migrations to run func=doMigration
time=2022-04-29T15:50:46Z level=info msg=instance account example.org CREATED with id 01MJ9FMWJN4QBMPKZ9W25G7107
time=2022-04-29T15:50:46Z level=info msg=created instance instance example.org with id 01HNRB6TTS4D7WZDA9SW0JZP87
panic: read /gotosocial/web/template: is a directory

goroutine 1 [running]:
html/template.Must(...)
        /usr/local/go/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0004676c0, {0xc0003dacc0, 0x19})
        /drone/src/vendor/github.com/gin-gonic/gin/gin.go:225 +0x2e6
github.com/superseriousbusiness/gotosocial/internal/router.loadTemplates(0x1db8080?)
        /drone/src/internal/router/template.go:51 +0x278
github.com/superseriousbusiness/gotosocial/internal/router.New({0x248dde8, 0xc000048018}, {0x24a57a8?, 0xc0002f52b0?})
        /drone/src/internal/router/router.go:186 +0x48a
github.com/superseriousbusiness/gotosocial/cmd/gotosocial/action/server.glob..func1({0x248dde8, 0xc000048018})
        /drone/src/cmd/gotosocial/action/server/server.go:101 +0x225
main.run({0x248dde8, 0xc000048018}, 0x205cfc0)
        /drone/src/cmd/gotosocial/common.go:58 +0x83
main.serverCommands.func2(0xc000485900?, {0x1faadb1?, 0x0?, 0x0?})
        /drone/src/cmd/gotosocial/server.go:42 +0x31
github.com/spf13/cobra.(*Command).execute(0xc000485900, {0x349ff08, 0x0, 0x0})
        /drone/src/vendor/github.com/spf13/cobra/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000485180)
        /drone/src/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /drone/src/vendor/github.com/spf13/cobra/command.go:902
main.main()
        /drone/src/cmd/gotosocial/main.go:90 +0x459
```
Thank you for your help.

**Comment by tsmethurst** [comment]
Hi! Can you tell us which version of GoToSocial you're using?

**Comment by tsmethurst** [comment]
Ah wait, I see the issue! Something is broken on `latest`. In your docker-compose.yaml file, could you please try changing `image: superseriousbusiness/gotosocial:latest` to `image: superseriousbusiness/gotosocial:0.3.1`? That should resolve your issue :)

**Comment by pvllnv** [comment]
Yes ! Thank you tobi !

**Comment by tsmethurst** [comment]
No problem :) just updated the documentation to avoid other people running into this same problem. Thanks for opening the issue! I'll close it now but feel free to reopen if you have more questions about this.
