### ISSUE TITLE
[bug] non-string environment variables can't be parsed using new config stuff

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#621]
When setting environment variable config through docker, non-string fields can't be parsed correctly, leading to panics:

```
gotosocial    | panic: 7 error(s) decoding:
gotosocial    | 
gotosocial    | * 'accounts-approval-required' expected type 'bool', got unconvertible type 'string', value: 'true'
gotosocial    | * 'accounts-reason-required' expected type 'bool', got unconvertible type 'string', value: 'false'
gotosocial    | * 'accounts-registration-open' expected type 'bool', got unconvertible type 'string', value: 'false'
gotosocial    | * 'letsencrypt-enabled' expected type 'bool', got unconvertible type 'string', value: 'false'
gotosocial    | * 'smtp-port' expected type 'int', got unconvertible type 'string', value: '587'
gotosocial    | * 'statuses-poll-max-options' expected type 'int', got unconvertible type 'string', value: '10'
gotosocial    | * 'statuses-poll-option-max-chars' expected type 'int', got unconvertible type 'string', value: '100'
gotosocial    | 
gotosocial    | goroutine 1 [running]:
gotosocial    | github.com/superseriousbusiness/gotosocial/internal/config.(*ConfigState).reloadFromViper(0xc000097880)
gotosocial    | 	/drone/src/internal/config/state.go:134 +0x53
gotosocial    | github.com/superseriousbusiness/gotosocial/internal/config.(*ConfigState).Viper.func1()
gotosocial    | 	/drone/src/internal/config/state.go:77 +0x25
gotosocial    | github.com/superseriousbusiness/gotosocial/internal/config.(*ConfigState).Viper(0x1d99180?, 0xc0003d58c0?)
gotosocial    | 	/drone/src/internal/config/state.go:81 +0xa5
gotosocial    | github.com/superseriousbusiness/gotosocial/internal/config.(*ConfigState).LoadEarlyFlags(0x4?, 0x206dcb0?)
gotosocial    | 	/drone/src/internal/config/state.go:89 +0xb9
gotosocial    | github.com/superseriousbusiness/gotosocial/internal/config.LoadEarlyFlags(...)
gotosocial    | 	/drone/src/internal/config/global.go:47
gotosocial    | main.main.func1(0xc000476780?, {0x1fbbc5b?, 0x0?, 0x0?})
gotosocial    | 	/drone/src/cmd/gotosocial/main.go:52 +0x26
gotosocial    | github.com/spf13/cobra.(*Command).execute(0xc000476780, {0x34c1068, 0x0, 0x0})
gotosocial    | 	/drone/src/vendor/github.com/spf13/cobra/command.go:835 +0x58b
gotosocial    | github.com/spf13/cobra.(*Command).ExecuteC(0xc000476500)
gotosocial    | 	/drone/src/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
gotosocial    | github.com/spf13/cobra.(*Command).Execute(...)
gotosocial    | 	/drone/src/vendor/github.com/spf13/cobra/command.go:902
gotosocial    | main.main()
gotosocial    | 	/drone/src/cmd/gotosocial/main.go:68 +0x194
```

It looks like we need to do some conversion and parsing; from GtS's perspective, all those environment variable settings come in as strings, so for non string values we need to try to coerce them into appropriate types

**Comment by NyaaaWhatsUpDoc** [comment]
I've added a PR for this here: https://github.com/superseriousbusiness/gotosocial/pull/622

But even running this locally before implementing my fix I couldn't seem to trigger this panic :thinking:

**Comment by tsmethurst** [comment]
Closed by https://github.com/superseriousbusiness/gotosocial/pull/625
