### ISSUE TITLE
[bugfix] Test inconsistencies / intermittent failures

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#762]
When running on the ci/cd platform there are tests that often fail and need to be rerun, and then on the second or third run they succeed. It's weird! These tend to be tests in the processor, in dereferencing, in the media package, and sometimes elsewhere. We should squash these bugs because it's very annoying having to rerun ci/cd multiple times to get a test to pass, and also it means that the tests aren't reliable!

**Comment by tsmethurst** [comment]
Some recent examples:

```
--- FAIL: TestInstancePatchTestSuite (9.10s)
    --- FAIL: TestInstancePatchTestSuite/TestInstancePatch2 (0.05s)
        suite.go:63: test panicked: db migration error: error creating storage backend: store/storage: storage lock already open
            goroutine 156 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc001081040)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x3e
            panic({0x1e15d60, 0xc0018412c0})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/log.Panic.func1()
            	/drone/src/internal/log/log.go:119 +0x2a
            github.com/superseriousbusiness/gotosocial/internal/log.Panic({0xc000171cb0, 0x1, 0x1})
            	/drone/src/internal/log/log.go:121 +0xd4
            github.com/superseriousbusiness/gotosocial/testrig.NewTestDB()
            	/drone/src/testrig/db.go:94 +0x165
            github.com/superseriousbusiness/gotosocial/internal/api/client/instance_test.(*InstanceStandardTestSuite).SetupTest(0xc00052e780)
            	/drone/src/internal/api/client/instance/instance_test.go:84 +0x73
            github.com/stretchr/testify/suite.Run.func1(0xc001081040)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:148 +0x1ee
            testing.tRunner(0xc001081040, 0xc0004ee900)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

```
--- FAIL: TestFromClientAPITestSuite (1.21s)
    --- FAIL: TestFromClientAPITestSuite/TestProcessStreamNewStatus (0.09s)
        suite.go:63: test panicked: failed to stop Worker pool
            goroutine 754 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc0000ceb60)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x3e
            panic({0x1decf00, 0xc0006d36c0})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/processing_test.(*ProcessingStandardTestSuite).TearDownTest(0xc001a4de60)
            	/drone/src/internal/processing/processor_test.go:120 +0x71
            github.com/stretchr/testify/suite.Run.func1.1()
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:141 +0x1db
            panic({0x1dad3e0, 0xc0006d3310})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/log.Panic.func1()
            	/drone/src/internal/log/log.go:119 +0x2a
            github.com/superseriousbusiness/gotosocial/internal/log.Panic({0xc002335c78, 0x1, 0x1})
            	/drone/src/internal/log/log.go:121 +0xd4
            github.com/superseriousbusiness/gotosocial/testrig.NewTestDB()
            	/drone/src/testrig/db.go:94 +0x165
            github.com/superseriousbusiness/gotosocial/internal/processing_test.(*ProcessingStandardTestSuite).SetupTest(0xc001a4de60)
            	/drone/src/internal/processing/processor_test.go:92 +0x3d
            github.com/stretchr/testify/suite.Run.func1(0xc0000ceb60)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:148 +0x1ee
            testing.tRunner(0xc0000ceb60, 0xc0021f1290)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

```
--- FAIL: TestInstancePatchTestSuite (8.50s)
    --- FAIL: TestInstancePatchTestSuite/TestInstancePatch1 (0.07s)
        suite.go:63: test panicked: db teardown: db was nil
            goroutine 8 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc0000be000)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x3e
            panic({0x1e13d40, 0xc00007d300})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/log.Panic.func1()
            	/drone/src/internal/log/log.go:119 +0x2a
            github.com/superseriousbusiness/gotosocial/internal/log.Panic({0xc00068f9a0, 0x1, 0x1})
            	/drone/src/internal/log/log.go:121 +0xd4
            github.com/superseriousbusiness/gotosocial/testrig.StandardDBTeardown({0x0, 0x0})
            	/drone/src/testrig/db.go:245 +0x65
            github.com/superseriousbusiness/gotosocial/internal/api/client/instance_test.(*InstanceStandardTestSuite).TearDownTest(0xc0004b2780)
            	/drone/src/internal/api/client/instance/instance_test.go:97 +0x29
            github.com/stretchr/testify/suite.Run.func1.1()
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:141 +0x1db
            panic({0x1e13d40, 0xc00007d2e0})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/log.Panic.func1()
            	/drone/src/internal/log/log.go:119 +0x2a
            github.com/superseriousbusiness/gotosocial/internal/log.Panic({0xc00068fcb0, 0x1, 0x1})
            	/drone/src/internal/log/log.go:121 +0xd4
            github.com/superseriousbusiness/gotosocial/testrig.NewTestDB()
            	/drone/src/testrig/db.go:94 +0x165
            github.com/superseriousbusiness/gotosocial/internal/api/client/instance_test.(*InstanceStandardTestSuite).SetupTest(0xc0004b2780)
            	/drone/src/internal/api/client/instance/instance_test.go:84 +0x73
            github.com/stretchr/testify/suite.Run.func1(0xc0000be000)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:148 +0x1ee
            testing.tRunner(0xc0000be000, 0xc000512b40)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

```
--- FAIL: TestAttachmentTestSuite (6.15s)
    --- FAIL: TestAttachmentTestSuite/TestDereferenceAttachmentAsync (2.90s)
        media_test.go:140: 
            	Error Trace:	media_test.go:140
            	Error:      	Received unexpected error:
            	            	no entries
            	Test:       	TestAttachmentTestSuite/TestDereferenceAttachmentAsync
        media_test.go:142: 
            	Error Trace:	media_test.go:142
            	Error:      	Expected value not to be nil.
            	Test:       	TestAttachmentTestSuite/TestDereferenceAttachmentAsync
        suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
            goroutine 20 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc001360680)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x3e
            panic({0x1d12ca0, 0x3378b00})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/federation/dereferencing_test.(*AttachmentTestSuite).TestDereferenceAttachmentAsync(0xc0013a6a00)
            	/drone/src/internal/federation/dereferencing/media_test.go:144 +0x372
            reflect.Value.call({0xc0012353e0?, 0xc00000f170?, 0xc000939080?}, {0x1f15e04, 0x4}, {0xc001df5e70, 0x1, 0xc001df5d80?})
            	/usr/local/go/src/reflect/value.go:556 +0x845
            reflect.Value.Call({0xc0012353e0?, 0xc00000f170?, 0xc0013a6a00?}, {0xc001df5e70, 0x1, 0x1})
            	/usr/local/go/src/reflect/value.go:339 +0xbf
            github.com/stretchr/testify/suite.Run.func1(0xc001360680)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:158 +0x4b6
            testing.tRunner(0xc001360680, 0xc00096c090)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

```
--- FAIL: TestManagerTestSuite (6.25s)
    --- FAIL: TestManagerTestSuite/TestSimpleJpegProcessAsync (0.39s)
        manager_test.go:371: 
            	Error Trace:	manager_test.go:371
            	Error:      	Received unexpected error:
            	            	no entries
            	Test:       	TestManagerTestSuite/TestSimpleJpegProcessAsync
        manager_test.go:372: 
            	Error Trace:	manager_test.go:372
            	Error:      	Expected value not to be nil.
            	Test:       	TestManagerTestSuite/TestSimpleJpegProcessAsync
        suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
            goroutine 219 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc000b08680)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x3e
            panic({0x1ca5800, 0x32ac2a0})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/media_test.(*ManagerTestSuite).TestSimpleJpegProcessAsync(0xc00012ca80)
            	/drone/src/internal/media/manager_test.go:376 +0x227
            reflect.Value.call({0xc00012d920?, 0xc00012bab0?, 0x0?}, {0x1ea362b, 0x4}, {0xc0007e3e70, 0x1, 0xc0007e3d80?})
            	/usr/local/go/src/reflect/value.go:556 +0x845
            reflect.Value.Call({0xc00012d920?, 0xc00012bab0?, 0xc00012ca80?}, {0xc0007e3e70, 0x1, 0x1})
            	/usr/local/go/src/reflect/value.go:339 +0xbf
            github.com/stretchr/testify/suite.Run.func1(0xc000b08680)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:158 +0x4b6
            testing.tRunner(0xc000b08680, 0xc00019d7a0)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

**Comment by tsmethurst** [comment]
Seems to have been closed by https://github.com/superseriousbusiness/gotosocial/commit/0245c606d77c8b99833ccc2c0923a298fb482236, https://github.com/superseriousbusiness/gotosocial/commit/39d98881b00abc540d0f819cd785eeae3ee81aa0, https://github.com/superseriousbusiness/gotosocial/pull/798/commits/201ff20fd7fad2c1c536df6335300aa6bb8f4c35
