### ISSUE TITLE
[bug] Media tests intermittent failures

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#819]
```
--- FAIL: TestManagerTestSuite (6.66s)
    --- FAIL: TestManagerTestSuite/TestSimpleJpegProcessAsync (0.48s)
        manager_test.go:371: 
            	Error Trace:	/drone/src/internal/media/manager_test.go:371
            	Error:      	Received unexpected error:
            	            	no entries
            	Test:       	TestManagerTestSuite/TestSimpleJpegProcessAsync
        manager_test.go:372: 
            	Error Trace:	/drone/src/internal/media/manager_test.go:372
            	Error:      	Expected value not to be nil.
            	Test:       	TestManagerTestSuite/TestSimpleJpegProcessAsync
        suite.go:77: test panicked: runtime error: invalid memory address or nil pointer dereference
            goroutine 228 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
            github.com/stretchr/testify/suite.failOnPanic(0xc000fa3380, {0x1cf65e0, 0x334fc90})
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:77 +0x3b
            github.com/stretchr/testify/suite.Run.func1.1()
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:161 +0x252
            panic({0x1cf65e0, 0x334fc90})
            	/usr/local/go/src/runtime/panic.go:838 +0x207
            github.com/superseriousbusiness/gotosocial/internal/media_test.(*ManagerTestSuite).TestSimpleJpegProcessAsync(0xc000482b60)
            	/drone/src/internal/media/manager_test.go:376 +0x1d5
            reflect.Value.call({0xc0000952c0?, 0xc00000ee60?, 0x658?}, {0x1ef7737, 0x4}, {0xc0008a5e70, 0x1, 0xc0008a5d80?})
            	/usr/local/go/src/reflect/value.go:556 +0x845
            reflect.Value.Call({0xc0000952c0?, 0xc00000ee60?, 0xc000482b60?}, {0xc0008a5e70, 0x1, 0x1})
            	/usr/local/go/src/reflect/value.go:339 +0xbf
            github.com/stretchr/testify/suite.Run.func1(0xc000fa3380)
            	/drone/src/vendor/github.com/stretchr/testify/suite/suite.go:175 +0x4b6
            testing.tRunner(0xc000fa3380, 0xc0001a99e0)
            	/usr/local/go/src/testing/testing.go:1439 +0x102
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:1486 +0x35f
```

**Comment by tsmethurst** [comment]
Haven't seen this one again recently, so thinking it's been resolved by recent changes... will open it again if i see it again
